# Generated by Django 3.2.5 on 2023-03-15 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generated',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_voice', models.FileField(upload_to='generated')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Generated',
                'verbose_name_plural': 'Generateds',
            },
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
